########################################
##                                    ##
##      EVOLUTION OF CELL FUSION      ##         _~
##         RUNNING SIMULATIONS        ##     _~ )_)_~
##          last edit: 01/18          ##    )_))_))_)
##        author: Anais Tilquin       ##    _!__!__!_ /
##          redsiana@orange.fr        ##    \______t/
##                                    ##  ~~~~~~~~~~~~~
########################################

# -------------------------------------------------------
# ########### Script description
# -------------------------------------------------------
#
# Runs simulations for the parameter sets generated by the script param_table.R
# Stores results (final freq of fusion, time to reach it) in this same table and 
# saves them in file RESULT.txt
#
# If a sim results in fixation, subsequent rows of the param_table with the same
# parameters but for a lower fusion rate are skipped, since they would also result
# in fixation. This to save computation time.


rm(list=ls())

source('PARAM_TABLE.R')                                                           # load parameters to run the simulations with, creates table .param
source('mitofunction.R')                                                          # load the function running the simulation

.sim <- 1

  while( .sim <= dim(.param)[1] ){
    
    rm(list = setdiff( ls(), lsf.str()) )
    
    ## run simulation for the set of parameters number .sim of table .param
    
    res <- mitofunction(Ka1 <- .param$Ka1 [.sim],
                 Ka2 <- .param$Ka2 [.sim],
                 bsline1 <- 1-Ka1,
                 bsline2 <- 1-Ka2,
                 B1 <- .param$B1 [.sim],
                 B2 <- .param$B2 [.sim],
                 M1 <- .param$M1 [.sim],
                 M2 <- .param$M2 [.sim],
                 Mito <- .param$Mito [.sim],
                 cost_sex <- .param$cost_sex [.sim],
                 rate_sex <- .param$rate_sex [.sim],
                 replacement <- .replacement,
                 josh <- .josh)
    
    print(paste(.sim, " / ", dim(.param)[1]))
    
    ## store results in the table .param
    
    .param$f[.sim] <- as.numeric( round(res[1], 4) )
    .param$time[.sim] <- as.numeric( res[2] )
    .param$h[.sim] <- as.numeric( res[3] )
    
    ## save workspace image every now and then in case shit happens
    
    if(.sim / 10 == round(.sim/10)) {
       save.image( file = paste('checkpoint',.sim, ".RData", sep="") )
    }
    
    ## to save time, for each parameter set, if fusion fixes with a given
    ## fusion rate, lower fusion rates are not investigated (as they will fix too)
    
    skip <- 1
    
    if( .param$f[.sim] > .99 ){
      
      while( .param$rate_sex[.sim + skip] != 1 & (.sim+skip) <= dim(.param)[1] ){
        skip <- skip + 1
      }
      .sim <- .sim + skip
      
      if( .sim >  dim(.param)[1] ){
        save.image( file = paste('RESULT',.sim, ".RData", sep="") )               # save session and data if end of param table has been reached
        write.table(.param, 'RESULT.txt')
      }
      
    } else {
      .sim <- .sim + 1
    }
    
  }
  
## save parameter table with results 

save.image( file = paste('RESULT',.sim, ".RData", sep="") )
write.table(.param, 'RESULT.txt')

source('titration.R')
